var State = require("./State")
var EducationMetric;

var EDUCATION_METRIC_TITLE = "EDUCATION_METRIC_TITLE";
var EDUCATION_METRIC_DATE = "EDUCATION_METRIC_DATE";
var EDUCATION_METRIC_ELAPSED_TIME = "EDUCATION_METRIC_ELAPSED_TIME";



EducationMetric = function (st, json) {
    this.STATE = st;
    this.EDUCATION_METRIC_TITLE = json[EDUCATION_METRIC_TITLE];
    this.EDUCATION_METRIC_DATE = json[EDUCATION_METRIC_DATE];
    this.EDUCATION_METRIC_ELAPSED_TIME = json[EDUCATION_METRIC_ELAPSED_TIME];
}

EducationMetric.id = "EDUCATION_METRIC_ID";
EducationMetric.EDUCATION_METRIC_TITLE = EDUCATION_METRIC_TITLE;
EducationMetric.EDUCATION_METRIC_DATE = EDUCATION_METRIC_DATE;
EducationMetric.EDUCATION_METRIC_ELAPSED_TIME = EDUCATION_METRIC_ELAPSED_TIME;

module.exports = EducationMetric;